name: Code Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm ts:check

      - name: Lint check
        run: pnpm lint
